[library.work]
files = [
    "pkg/**/*.vhd",
    "rtl/soc/**/*.vhd",
    "rtl/perips/**/*.vhd",
    "sim/soc/**/*.vhd"
]

[library.single_cycle]
files = [
    "rtl/core/single_cycle/**/*.vhd",
    "sim/core/single_cycle/**/*.vhd"
]

[library.multi_cycle]
files = [
    "rtl/core/multi_cycle/**/*.vhd",
    "sim/core/multi_cycle/**/*.vhd"
]